;; -*- mode:lisp -*-
;;
;; Color theme definitions.

(in-package :lem-user)

(define-color-theme "xcode" ()
  (:display-background-mode :light)
  (:foreground "#000000")
  (:background "#ffffff")
  (:inactive-window-background nil)
  (cursor :foreground "#ffffff" :background "#000000")
  (region :foreground nil :background "#FFFFFF")
  (modeline :background "grey" :foreground "white")
  (modeline-inactive :background "#303030" :foreground "gray")
  (syntax-string-attribute :foreground "#d70000")
  (syntax-comment-attribute :foreground "#008000")
  (syntax-keyword-attribute :foreground "#af0087")
  (syntax-constant-attribute :foreground "#ff00ff")
  (syntax-function-name-attribute :foreground "#A4CDFF")
  (syntax-variable-attribute :foreground "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff"))

(define-color-theme "xcode-dark" ("xcode")
  (:display-background-mode :dark)
  (:foreground "#ffffff")
  (:background "#202020")
  (cursor :background "white")
  (region :foreground "#FFFFFF" :background "#343434")
  (modeline :bold t :background "#292929" :foreground "#FFFFFF")
  (modeline-inactive :bold t :background "#383838" :foreground "white")
  (lem-core::modeline-name-attribute :foreground "#5DD8FF")
  (lem-core::inactive-modeline-name-attribute :foreground "#5d6dff")
  (lem-core::modeline-major-mode-attribute :foreground "#5DD8FF")
  (lem-core::inactive-modeline-major-mode-attribute :foreground "#5d6dff")
  (lem-vi-mode/modeline::state-modeline-yellow :foreground "grey" :reverse t)
  (lem-vi-mode/modeline::state-modeline-orange :foreground "#41B645" :reverse t)
  (lem-vi-mode/modeline::state-modeline-green :foreground "#A2E474" :reverse t)
  (syntax-string-attribute :foreground "#FC6A5D")
  (syntax-comment-attribute :foreground "#6C7986")
  (syntax-keyword-attribute :foreground "#FC5FA3")
  (syntax-constant-attribute :foreground "#A167E6")
  (syntax-function-name-attribute :foreground "#67B7A4")
  (syntax-variable-attribute :foreground "#67B7A4")
  (syntax-type-attribute :foreground "#9EF1DD"))

(define-color-theme "doom-one" ()
  (:display-background-mode :dark)
  (:foreground "#bbc2cf")
  (:background "#282c34")
  (:inactive-window-background nil)
  (cursor :background "#51afef")
  (region :foreground nil :background "#2257A0")
  ;; Syntax
  (syntax-string-attribute :foreground "#98be65")
  (syntax-comment-attribute :foreground "#5B6268")
  (syntax-keyword-attribute :foreground "#51afef")
  (syntax-constant-attribute :foreground "#a9a1e1")
  (syntax-function-name-attribute :foreground "#c678dd")
  (syntax-variable-attribute :foreground "#dcaeea")
  (syntax-type-attribute :foreground "#ECBE7B")
  (syntax-builtin-attribute :foreground "#c678dd")
  (syntax-warning-attribute :foreground "#ff6c6b")
  ;; Modeline
  (modeline :background "#1c1f24" :foreground "#bbc2cf")
  (modeline-inactive :background "#21242b" :foreground "#5B6268")
  (lem-core::modeline-name-attribute :foreground "#51afef" :bold t)
  (lem-core::inactive-modeline-name-attribute :foreground "#3f444a")
  (lem-core::modeline-major-mode-attribute :foreground "#c678dd")
  (lem-core::inactive-modeline-major-mode-attribute :foreground "#3f444a")
  (lem-core::modeline-minor-modes-attribute :foreground "#73797e")
  (lem-core::inactive-modeline-minor-modes-attribute :foreground "#3f444a")
  (lem-core::modeline-position-attribute :foreground "#9ca0a4" :background "#1c1f24")
  (lem-core::inactive-modeline-position-attribute :foreground "#3f444a" :background "#21242b")
  (lem-core::modeline-posline-attribute :foreground "#282c34" :background "#51afef")
  (lem-core::inactive-modeline-posline-attribute :foreground "#282c34" :background "#2257A0")
  ;; Vi mode modeline states
  (lem-vi-mode/modeline::state-modeline-yellow :foreground "#282c34" :background "#51afef" :bold t)
  (lem-vi-mode/modeline::state-modeline-orange :foreground "#282c34" :background "#c678dd" :bold t)
  (lem-vi-mode/modeline::state-modeline-green :foreground "#282c34" :background "#98be65" :bold t)
  ;; Line numbers
  (lem/line-numbers:line-numbers-attribute :foreground "#3f444a" :background "#282c34")
  (lem/line-numbers:active-line-number-attribute :foreground "#bbc2cf" :background "#282c34")
  ;; Frame multiplexer
  (lem/frame-multiplexer:frame-multiplexer-active-frame-name-attribute
   :foreground "#282c34" :background "#51afef" :bold t)
  (lem/frame-multiplexer:frame-multiplexer-frame-name-attribute
   :foreground "#282c34" :background "#3f444a" :bold t)
  (lem/frame-multiplexer:frame-multiplexer-background-attribute
   :foreground "#51afef" :background "#1c1f24")
  ;; Paren coloring
  (lem-lisp-mode/paren-coloring:paren-color-1 :foreground "#ff6c6b")
  (lem-lisp-mode/paren-coloring:paren-color-2 :foreground "#da8548")
  (lem-lisp-mode/paren-coloring:paren-color-3 :foreground "#ECBE7B")
  (lem-lisp-mode/paren-coloring:paren-color-4 :foreground "#98be65")
  (lem-lisp-mode/paren-coloring:paren-color-5 :foreground "#46D9FF")
  (lem-lisp-mode/paren-coloring:paren-color-6 :foreground "#c678dd")
  ;; Documents (Markdown, Org, etc.)
  (lem:document-header1-attribute :foreground "#51afef" :bold t)
  (lem:document-header2-attribute :foreground "#46D9FF" :bold t)
  (lem:document-header3-attribute :foreground "#98be65" :bold t)
  (lem:document-header4-attribute :foreground "#ECBE7B" :bold t)
  (lem:document-header5-attribute :foreground "#da8548" :bold t)
  (lem:document-header6-attribute :foreground "#ff6c6b" :bold t)
  (lem:document-bold-attribute :bold t)
  (lem:document-italic-attribute :foreground "#a9a1e1")
  (lem:document-underline-attribute :underline t)
  (lem:document-link-attribute :foreground "#51afef" :underline t)
  (lem:document-list-attribute :foreground "#46D9FF")
  (lem:document-code-block-attribute :background "#21242b" :foreground "#bbc2cf")
  (lem:document-inline-code-attribute :background "#21242b" :foreground "#98be65")
  (lem:document-blockquote-attribute :foreground "#5B6268")
  (lem:document-table-attribute :foreground "#bbc2cf" :background "#21242b"))
